steps:
# 1. Build Docker image
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA', '.']
# 2. Push Docker image ke Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA']
# 3. Deploy ke Cloud Run
- name: 'gcr.io/google-appengine/exec-wrapper'
args:
- '-i'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
- '-s'
- 'my-flask-app'
- '--'
- 'gcloud'
- 'run'
- 'deploy'
- 'my-flask-app'
- '--image'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
- '--region'
- 'us-central1'
- '--platform'
- 'managed'
- '--allow-unauthenticated'
# Simpan image yang di-deploy untuk referensi
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
