steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
  - name: 'gcr.io/google-cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'my-flask-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY # Or NONE
