steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
  - name: 'gcr.io/google-cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'my-flask-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-app-repo/my-flask-app:$SHORT_SHA'
options:
  # Replace 'your-logs-bucket' with the name of your Cloud Storage bucket
  # It should be in the format 'gs://your-bucket-name'
  logsBucket: 'gs://flask-app-demo1321'
  # If you are using a custom service account, specify it here
  # serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/your-custom-service-account@$PROJECT_ID.iam.gserviceaccount.com'
